repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
  - repo: https://github.com/standard/standard
    rev: v17.1.2
    hooks:
      - id: standard
  - repo: https://github.com/google/yamlfmt
    rev: v0.19.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
