---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-yaml
  - id: end-of-file-fixer
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys]
- repo: https://github.com/standard/standard
  rev: v17.0.0
  hooks:
  - id: standard
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.2
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0']
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
  - id: mdformat
